[package]
name = "pool-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pool_sync"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/bin/example.rs"


[dependencies]
anyhow = "1.0.82"
tokio = {version = "1.37.0", features = ["rt-multi-thread", "macros"]}
dotenv = "0.15.0"
#alloy = {vesrion = "0.1.2", features = ["full"]}
serde = {version = "1.0.203", features = ["derive"]}
async-trait = "0.1.80"
alloy = { git = "https://github.com/alloy-rs/alloy",  features = [
    "contract",
    "network",
    "node-bindings",
    "providers",
    "provider-http",
    "json-abi",
    "pubsub",
    "provider-ipc",
    "provider-ws",
    "rpc-client",
    "rpc-client-ipc",
    "rpc-client-ws",
    "rpc-types-eth",
    "rpc-types-trace",
    "signers",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-yubihsm",
] }
alloy-sol-types = { version = "0.7.4", features = ["json"]}
alloy-sol-macro = { version = "0.7.4", features = ["json"]}
alloy-contract = { git = "https://github.com/alloy-rs/alloy"}
